from pydantic import BaseModel, Field, ConfigDict
from uuid import UUID
from datetime import datetime
from typing import Optional

class paymentsrequest(BaseModel):
    # userid changed to merchant_id to match our database analytics schema
    merchant_id: str = Field(..., max_length=50, description="Unique identifier for the merchant")
    amount: float = Field(..., gt=0, description="Payment amount must be greater than 0")
    currency: str = Field(default="INR", min_length=3, max_length=3, description="3-letter currency code")
    
    # Note: idempotency_key is intentionally NOT here because it comes from the HTTP Header, 
    # not the JSON body payload.

class paymentsresponse(BaseModel):
    # transaction_id is the actual primary key generated by the database
    transaction_id: UUID
    idempotency_key: str
    merchant_id: str
    amount: float
    currency: str
    status: str
    created_at: datetime
    
    # This configuration is required for FastAPI to automatically convert 
    # your SQLAlchemy database object into this JSON format.
    model_config = ConfigDict(from_attributes=True)
