"""canonical domain schema

Revision ID: 6c144777fd83
Revises: 
Create Date: 2026-10-05 21:39:03.305672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c144777fd83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id', name=op.f('pk_merchants'))
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_payments_amount_minor_positive')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_payments_currency_length')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], name=op.f('fk_payments_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_merchant_id_created_at', 'payments', ['merchant_id', 'created_at'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.CHAR(length=64), nullable=False),
    sa.Column('state', sa.Enum('PROCESSING', 'COMPLETED', name='idempotency_state'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], name=op.f('fk_idempotency_records_merchant_id_merchants')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], name=op.f('fk_idempotency_records_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('merchant_id', 'idempotency_key', name='uq_idempotency_records_merchant_id_idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('idempotency_records')
    op.drop_index('ix_payments_merchant_id_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_table('merchants')
    # create_table() creates these enum types implicitly but drop_table() does
    # not remove them, so without this a downgrade/upgrade cycle fails with
    # "type already exists". Dropped after the tables that reference them.
    sa.Enum(name='idempotency_state').drop(op.get_bind())
    sa.Enum(name='payment_status').drop(op.get_bind())
